### ISSUE TITLE
verdaccio 5 support?

### ISSUE THREAD

**Issue by migasQ** [SzymonDukla/verdaccio-gitlab-oauth2#1]
Is verdaccio 5 actually supported? 

I did the following (node 12)
- `npm install verdaccio verdaccio-gitlab-oauth2`
- with config
```
storage: ./storage

auth:
  gitlab-oauth2:
    group: https://gitlab.com/mygroup/mysubgroup
    client-id: xxx
    client-secret: xxx

# a list of other known repositories we can talk to
uplinks:
  npmjs:
    url: https://registry.npmjs.org/

packages:
  '**':
    access: $authenticated
    publish: $authenticated
    proxy: npmjs

middlewares:
  gitlab-oauth2:
    enabled: true

# log settings
logs: {type: stdout, format: pretty, level: http}
```
- verdaccio starts without problems
```
 warn --- config file  - /Users/Jens/Documents/SFM_Systems_Dev/services-compose/verdaccio/conf/config.yaml
gitlab-oauth2] Proxy config: {"HTTP_PROXY":null,"HTTPS_PROXY":null,"NO_PROXY":null}
 warn --- Plugin successfully loaded: verdaccio-gitlab-oauth2
gitlab-oauth2] Proxy config: {"HTTP_PROXY":null,"HTTPS_PROXY":null,"NO_PROXY":null}
 warn --- Plugin successfully loaded: verdaccio-gitlab-oauth2
 warn --- http address - http://localhost:4873/ - verdaccio/5.1.1

```
- In verdaccio there is no Gitlab button, just the regular login window
- When I try to use it the logs show
```
gitlab-oauth2 Response code 401 (Unauthorized)
gitlab-oauth2 Unauthenticated: user "xxx" is not a member of "https://gitlab.com/mygroup/mysubgroup"
 error--- authenticating for user xxxfailed. Error: bad username/password, access denied
 http --- 401, user: null(127.0.0.1), req: 'POST /-/verdaccio/login', error: bad username/password, access denied
```

So where is my error? Should there be a Gitlab login button or should I login with Gitlab user/ pass in verdaccio? We are using 2fa so I was taking my personal access token, could that be an issue?

**Comment by SzymonDukla** [comment]
Hello @migasQ 
as `group` you should insert only `mygroup`.
There was, sometimes, a problem with button CSS IDs to attach the script to the login button.
Please fix first the issue of the `group` parameter to resolve the error from logs and then check whether the script is properly attached to intercept login button clicks.

**Comment by migasQ** [comment]
Thanks for your reply. I replaced the the group with just `mygroup` but still the same error. The application is created in gitlab as a group application for the group `mygroup`. The user has 2fa activated but I use a personal access token for login (of course I also tried the regular password), the error is always the same. Any further ideas?

**Comment by migasQ** [comment]
What I just noticed: Clicking on this login button just opens the regular login dialog. That is not supposed to happen right?

<img width="988" alt="button1" src="https://user-images.githubusercontent.com/14925258/125124340-34f64c80-e0f8-11eb-913b-efc655fc8b93.png">

<img width="878" alt="button2" src="https://user-images.githubusercontent.com/14925258/125124333-3293f280-e0f8-11eb-8767-1148f5f3d357.png">

**Comment by migasQ** [comment]
Any ideas?

**Comment by migasQ** [comment]
No idea why I cannot get it to work. With `verdaccio@4` it works quite fine. I also checked the changes in in the underlying github project which were affecting the login button: https://github.com/n4bb12/verdaccio-github-oauth-ui/commit/997a789c3831c903db79114c642aefbc63555bfb#diff-93e4958f5abd3d914baa71288571afd419d04ed641994c269c85ddd583c9c835

And changed it in a local build of the package. But in `verdaccio@5` I cannot get the OAUTH url to be triggered, always the regular login dialog is shown.

**Comment by denhub** [comment]
> What I just noticed: Clicking on this login button just opens the regular login dialog. That is not supposed to happen right?
> 
> <img alt="button1" width="988" src="https://user-images.githubusercontent.com/14925258/125124340-34f64c80-e0f8-11eb-913b-efc655fc8b93.png">
> 
> <img alt="button2" width="878" src="https://user-images.githubusercontent.com/14925258/125124333-3293f280-e0f8-11eb-8767-1148f5f3d357.png">

I faced this problem too. The problem is that the changes are not applied to HTML.

I commented `return html;` in `/dist/server.js`.

Quick fix for docker usage without fork/rebuild `verdaccio-gitlab-oauth2`:

```
sed -i -- "s/return html;/\/\/ return html;/g" /usr/local/share/.config/yarn/global/node_modules/verdaccio-gitlab-oauth2/dist/server.js
```
